version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.4
        environment:
          ANSIBLE_REMOTE_USER: ubuntu
          TEST_HOSTS: integration/hosts
    steps:
      - checkout
      - run:
        command: |
          sudo pip install virtualenv
      - run:
          name: Run tests
          command: cd tests && make test
