version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.4
    steps:
      - checkout
      - run:
          command: sudo apt-get update -qq && sudo apt-get install -qq python-dev
      - run:
          command: sudo pip install virtualenv
      - run:
          name: Run tests
          command: cd tests && make test
          environment:
            TEST_HOSTS: integration/hosts
            ANSIBLE_HOST_KEY_CHECKING: False
            ANSIBLE_REMOTE_USER: ubuntu
