#!/bin/sh

# This script watches for changes to the haproxy configuration files and
# triggers a reload of haproxy.  The actual reload is performed by the
# haproxy-reload script.

# It is important to note that haproxy.conf and backend.map are not contained
# in any of the watched directories, since these files are regenerated upon
# restart.  Otherwise each restart would immediately trigger another restart.
inotifywait -e close_write -e move -e delete -m -q -r \
            {{ LOAD_BALANCER_CERTS_DIR }} {{ LOAD_BALANCER_CONF_DIR }} \
            {{ LOAD_BALANCER_BACKENDS_DIR }} |
    while read path event file; do
        touch {{ LOAD_BALANCER_RELOAD_FILE }}
    done
